---
title: 'LAB9: TEXT ANALYSIS'
author: "Soundarya G"
date: "05/04/2021"
output: word_document
---


```{r}
library("NLP")
library("tm")
library("RColorBrewer")
library("wordcloud")
library("wordcloud2")
```


```{r}
#to import the file type

filePath<-"dairy.txt"

#Read lines in text_file using readLine() function.
#And storing text-data to modified text_file.
text_file <- readLines(filePath)
text_file
```


```{r}
#Now we are using paste() function in text_file and make it a chunk and the
#text collapse into quotations (“ ”). And storing to text_file1.
text_file1 <- paste(text_file, collapse = " ")
head(text_file1)
```


```{r}
#The text mining function is used to convert the text to lower case,
#to remove unnecessary white space, to remove common stop words like ‘the’, “we”,
#to remove words, etc.
#Let us make text_file1 to lower case using tolower() function.
#And assign it to modified clean_text.

clean_text <- tolower(text_file1)
clean_text
head(clean_text)
```


```{r}
#In every step, you can modify your text-data and use it in
#the next step for text-manipulation. You can also remove
#Punctuation and digits
#with removeNumbers and removePunctuation arguments.
#To remove punctuations we are using gsub() function in the below code.
#Here, pattern= “\\W’’ to remove punctuations.
#Here, pattern= “\\d’’ to remove digits.
#replace= “_”, we are going to replace the punctuations by space.
#If we don’t do so then it may make new words.

clean_text1 <- gsub(pattern = "\\W", replace = " " ,clean_text)
head(clean_text1)
clean_text2 <- gsub(pattern = "\\d", replace = " ", clean_text1)
head(clean_text2)
```


```{r}
#The information value of ‘stopwords’ is near zero due to the fact that they are
#so common in a language.
#Extracting this kind of words is helpful before further analyses.

stopwords()
```


```{r}
#Lets us remove those stopwords and unnecessary words by using
#removeWords() function.
clean_text3 <- removeWords(clean_text2,words = c(stopwords(),"ai","â"))
head(clean_text3)
```


```{r}
#Now let us remove single letters, by gsub() function

clean_text4 <- gsub(pattern = "\\b[A-z]\\b{1}", replace = " ", clean_text3 )
head(clean_text4)
```


```{r}
#Here \\b[A-z] represents strings with any letter between a-z.
#The string can take uppercase letters as well as lower case letters
#and subset \\{1} says that the strings end with length one.
#We can finally remove white spaces using stripWhitespace() function,
#which is a part of tm library.

clean_text5 <- stripWhitespace(clean_text4)
head(clean_text4)
```


```{r}
#We now have a chunk of lines, and we are looking for the counting words.
#And already joined various lines and made a chunk.
#So first split individual words and add space between them as
#split using split() function.

clean_text6 <- strsplit(clean_text5, " ")
head(clean_text6)
```


```{r}
#Now create word_freq table and assign clean_text6 data in the
#table using table function.
word_freq <- table(clean_text6)
head(word_freq)
```


```{r}
#By using cbind() by taking word_freq data-frame arguments and
#combine by columns or rows, respectively.

word_freq1 <- cbind(names(word_freq), as.integer(word_freq))
head(word_freq1)
```


```{r}
# Generate the Word cloud
# The feature of words can be illustrated as a word cloud as follow:
# Word clouds add clarity and simplicity.
# The most used keywords stand out better in a word cloud.
# Word clouds are a dynamic tool for communication.
# Easy to understand, to be shared and are impressive words representation.
# Arguments of the word cloud generator function:
# words: the words to be plotted i.e.; word cloud where we have saved the text-data.
# Freq: word frequencies
# min.freq: words with a frequency below min.freq will not be plotted.
# max .words: maximum number of words to be plotted
# random.order: plot words in random order. If false, then words will be plotted in decreasingfrequency
# Rot.per: to adjust proportion words with 90-degree rotation (vertical text)
# colors: colour words from least to most frequent. Use, for example, colors = “Red” for asingle colour or “random-dark”, “random-light”.

word_cloud <- unlist(clean_text6)
wordcloud(word_cloud)
```


```{r}
wordcloud(word_cloud,min.freq = 5,random.order = FALSE,scale=c(3, 0.5))
wordcloud(word_cloud,min.freq = 3, max.words=1000, random.order=F, rot.per=0.2,
colors=brewer.pal(5,"Dark2"), scale=c(4,0.2))
wordcloud2(word_freq)
```


```{r}
wordcloud2(word_freq, color ="random-dark", backgroundColor = "white")
```

